name: timelapse_env

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-image
  - tifffile
  - tqdm
  - pip

  - pytorch
  - torchvision
  - torchaudio

  - pip:
      - cellpose
      - aicspylibczi